org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

publish.groupId=com.justeattakeaway
publish.artifactId=interval-annotated-string

publish.versionName=0.1.0-rc01

publish.pom.name=Interval Annotated String
publish.pom.description=This small Android utility library makes it easy to create and manage embedded links and styles within localized text.
publish.pom.url=https://github.com/justeattakeaway/IntervalAnnotatedString
